server:
  port: 8090
  servlet:
    context-path: /v1/prueba-service

spring:
  application:
    name: prueba-service

  datasource:
    url: jdbc:postgresql://ec2-52-0-114-209.compute-1.amazonaws.com:5432/d7qaqn765gt6lj
    username: uthkswthggnyby
    password: 870e972eecedfff8fd63cffc0eec3b1e220c96e2c2bec1686ffe6c1a7b25add3
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 12000

    initialization-mode: always
    data: classpath:cliente/cliente.sql,classpath:producto/producto.sql,classpath:reclamo/reclamo.sql

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true